### ISSUE TITLE
Access permissions

### ISSUE THREAD

**Issue by Eyal-R** [NationalLibraryofIsrael/API#1]
שלום לכולם
כרגע הספרייה הלאומית בתהליך מתן הרשאות לאוספים - לכן אם אתם מקבלים HTTP 403 Forbidden זה לא אומר שיש תקלה.
נעדכן עוד בהמשך!

**Comment by ericman93** [comment]
איך אפשר לקבל הרשאות?

**Comment by Eyal-R** [comment]
@ericman93 
ההרשאות יינתנו באופן גורף לכולם, ללא ביצוע Login.

**Comment by goolig** [comment]
את "מרחבי החיפוש" (מפות, תמונות וכו') תפרסמו עם תחילת האקטון או שזה מתועד במקום כלשהו?

**Comment by Eyal-R** [comment]
בשבוע הבא יעלה באתר ההאקתון דף תיאור על כל אוסף שיכלול גם את הפרמטר/ים המתאים/ים לו ב-Search API.

**Comment by Eyal-R** [comment]
Access was granted to all of our collections.
