### ISSUE TITLE
Available resources

### ISSUE THREAD

**Issue by ericman93** [NationalLibraryofIsrael/API#2]
כרגע מהתיעוד לפחות לא ברור מה אפשר לקבל מהAPI
אשמח לפירוט של כל המשאבים האפשריים
תודה!

**Comment by Eyal-R** [comment]
שלום רב,
התיעוד של ה-API הוא טכני בלבד.

באמצעות ה-API ניתן לבצע:
1. חיפוש פריטים (Search API)
2. גישה לפריטים (Presentation API +Image API)

אם שאלתך היא מבחינת התוכן, מיהם ומהם הפריטים שניתן לקבל - במהלך השבוע הבא יעלה באתר ההאקתון ( http://hackathon.nli.org.il ) פירוט של האוספים המשתתפים בהאקתון לרבות אופן הגישה לכל אוסף באמצעות ה-Search API.

במידה ויש שאלות טכניות נוספות, נשמח לענות.
שאלות תוכן יש להפנות ל-hackathon@nli.org.il
