### ISSUE TITLE
How do I combine tiles?

### ISSUE THREAD

**Issue by GiladFex** [NationalLibraryofIsrael/API#3]
Hi! I wanted to ask a quick question - if I want a better resolution of an image - how do I combine tiles into a single picture.

Thanks!

**Comment by Eyal-R** [comment]
You don't combine. The combination is done when presenting all the tiles to the user, for the user it looks like a complete image.

In other words, you need to render the requests only when you actually display an image to an end user. The image requests should be calculated carefully - asking for tiles that match the user's screen resolution, and desired zoom level.
It should be noted There are lots of libraries that do that for you - the display thing, you shouldn't develop that mechanism from scratch. A gross example is [project Mirador](http://projectmirador.org)

Tech team
National Library of Israel

**Comment by GiladFex** [comment]
I want to send it to an external API and using low quality version of the image doesnt fully work properly..

Thanks

**Comment by Eyal-R** [comment]
Does the external API can do harvest or must it get the stream in an upload?

**Comment by GiladFex** [comment]
the second option - i must send the photo to the api in order to get results.

**Comment by NLI-API** [comment]
Are you using Google API?
It seems that you would need to combine the tiles. You can develop a feeder (perhaps this was already developed elsewhere) that combine tiles and upload them to the API (you don't need to actually save it somewhere).

**Comment by GiladFex** [comment]
I _am_ using Google API too, and some less known ones as well 😄 

Thanks! I hope this will work smoothly.
