### ISSUE TITLE
Fail to get results using (Search) API

### ISSUE THREAD

**Issue by aynatgithub** [NationalLibraryofIsrael/API#5]
I get an HTTP error from Search API: "HTTP Status 403 - IP address rejected".

This happens in multiple examples from the Hackathon videos, for instance:

http://primo.nli.org.il/PrimoWebServices/xservice/search/brief?institution=NNL&loc=local,scope:(NNL_Ephemera)&query=any,contains,%D7%9B%D7%A8%D7%96%D7%95%D7%AA&query=lsr41,exact,yes&indx=1&bulkSize=50
http://primo.nli.org.il/PrimoWebServices/xservice/search/brief?institution=NNL&loc=local,scope:(NNL)&query=title,contains,%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D&indx=1&bulkSize=50

**Comment by prilia** [comment]
Hi, 
You get this errors because you are not connected throw the network of NLI.
When you'll be in NLI hackathon the response will be ok.

**Comment by prilia** [comment]
Please, also take a look at this issue
https://github.com/NationalLibraryofIsrael/API/issues/6
