### ISSUE TITLE
Catalog identifiers in API

### ISSUE THREAD

**Issue by aynatgithub** [NationalLibraryofIsrael/API#6]
We need to access multiple images in the Ephemera collection for our activity in the hackathon, and what we have are catalog identifiers (strings like 700255658). 
What field/value does this match in the API, and which API should we use (Presentation? Image?).

**Comment by prilia** [comment]
Hi,
If you using with Ephemera, you have a guide for this here:
http://web.nli.org.il/sites/NLI/Hebrew/Documents/EPHEMERA.pdf
in the last page there is an explanation about the fields/values that you can use in search api.
![image](https://user-images.githubusercontent.com/2115212/33128426-0627b862-cf95-11e7-8e12-f486a31dc0e0.png)
Here is result for example:

[output_search_primo.txt](https://github.com/NationalLibraryofIsrael/API/files/1496029/output_search_primo.txt)


After you get the result set for your search, you can choose to use the data for presentation api.


In field recordid you get the item id, ( NNL_Ephemera700267909 ) there is a id for presentation api.
http://iiif.nli.org.il/IIIFv21/DOCID/NNL_Ephemera700267909/manifest

After you get the manifest, you can use the data for get images from image api:
http://iiif.nli.org.il/IIIFv21/FL9706169/full/max/0/default.jpg

Currently the search is available only from NLI ip, so you can do search when you'll be in hackathon.

Please, take a look at all collections:
http://iiif.nli.org.il/collections/root.json
For Ephemera collection:
http://iiif.nli.org.il/collections/ephemera.json
