### ISSUE TITLE
Cannot connect to server 35.205.164.99

### ISSUE THREAD

**Issue by Odelya** [NationalLibraryofIsrael/API#8]
ping -c5 35.205.164.99 || echo 'Server down'
PING 35.205.164.99 (35.205.164.99): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3

--- 35.205.164.99 ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
Server down

**Comment by prilia** [comment]
Hi,
Currently the servers are down till tomorrow.
Server for your usage from the start of hackathon.
